### ISSUE TITLE
버그제보

### ISSUE THREAD

**Issue by alstn8022** [noonmaru/inv-captive#1]
인벤토리가 잠겨있을 때는 방벽으로 나타나져있는데 방벽을 들고 아주 빠르게 우클릭을 계속 하면 블록을 쌓을 수도 있고, 매크로(제 개인 서버에서만 사용)쓰니까 블록이 인벤창에서 사라지다가 나갔다가 들어오거나 기다리면 다시 들어오는 버그가 있습니다. 고칠 수 있는 문제라면 고쳐주셨으면 합니다.

**Comment by RedoC-github** [comment]
@alstn8022 님,
깃허브 커뮤니티 첫번째 활동을 축하합니다.

모든 플러그인들은 **사용자가 정상적인 플레이를 한다**라는 전제 하에서 제작됩니다. 위 이슈의 경우, 사용자가 비정상적인, 혹은 고의적인 플레이로 인한 오류이므로, 사용자의 플레이에 방해가 되는 요소인 ***버그***라고 정의할 수 없습니다만, 자신이 찾은 문제를 바로 이슈로 알려주신 것은 매우 바람직합니다.

감사합니다
