### ISSUE TITLE
코틀린관련 에러가 납니다

### ISSUE THREAD

**Issue by asd10384** [noonmaru/inv-captive#10]
org.bukkit.plugin.UnknownDependencyException: Unknown dependency Kotlin. Please download and install Kotlin to run this plugin.

어떻게 해결해야 할까요?
자세히 알려주시면 감사 하겠습니다.

**Comment by blue1222** [comment]
Kotlin 플러그인이 없어서 생기는 오류입니다. [여기](https://github.com/noonmaru/kotlin-plugin)에서 플러그인 다운로드 가능합니다

**Comment by asd10384** [comment]
감사합니다 해결되었습니다.
