### ISSUE TITLE
spigot으로 서버를 처음 열었는데 어떻게 하는지 잘 모르겠습니다.

### ISSUE THREAD

**Issue by brimstone07** [noonmaru/inv-captive#16]
이 플러그인이 무슨 파일이 필요한지도 jar 파일도 안나와있어서 너무나도 하고싶은데 하질 못합니다.. 5시간 찾아도 안나오더라고요. 
무슨 종류의 서버를 열어야하는지
버전은 뭐로 해야 하는지
옵티파인으로 들어가도 되는지
jar 파일 링크나 제 이메일로 보내주실수 있을까요?
위 이슈 보니까 프로토콜인가 코틀린이 필요하시다고 하던데 전 그게 뭔지도 잘 모르겠습니다. 서버여는법은 다 아는데 위에서 다운받으라는거 두개 ( 프로토콜 뭐시기, 코틀린 ) 다운받았더니 jar 파일이여서 플러그인 함에 넣으라고 하셔서 넣었더니 뭐 되는게 없더라고요.
/plugins 했더니 protoco...// 머시기머시기라고 뜨네요. 어떻게 해야하나요..
P.S. .plugins 말고 captive인가 그 명령어는 자체가 안떠요..

**Comment by alsrjs0725** [comment]
Paper 버킷을 사용해서 열어야 하며 버전은 제 기준으로는 1.16.3으로 플레이 할 경우에는 잘 플레이 되었습니다
Paper 버킷은 아래 링크에서 다운받으실 수 있습니다
https://papermc.io/downloads

이 플러그인을 구동하기 위한 필수 플러그인으로 Kotlin, ProtocolLib 플러그인이 필요하며 이 플러그인들은 아래 링크에서 받으실 수 있습니다
Kotlin : https://github.com/noonmaru/kotlin-plugin/releases
ProtocolLib : https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

**Comment by brimstone07** [comment]
> Paper 버킷을 사용해서 열어야 하며 버전은 제 기준으로는 1.16.3으로 플레이 할 경우에는 잘 플레이 되었습니다
> Paper 버킷은 아래 링크에서 다운받으실 수 있습니다
> https://papermc.io/downloads
> 
> 이 플러그인을 구동하기 위한 필수 플러그인으로 Kotlin, ProtocolLib 플러그인이 필요하며 이 플러그인들은 아래 링크에서 받으실 수 있습니다
> Kotlin : https://github.com/noonmaru/kotlin-plugin/releases
> ProtocolLib : https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/

페이퍼로 열고 코틀린과 프로토콜립만 넣으면 captive가 되냐요? 다른건 다운받아야 할게 없나요?

**Comment by devil0414** [comment]
네

**Comment by brimstone07** [comment]
> 네

안되는..

**Comment by qogusdn1017** [comment]
1.16.3 페이퍼 바로 [여기](https://papermc.io/api/v1/paper/1.16.3/latest/download)서 다운로드가 가능합니다.
또한 월드자체 시드를 불러오는 플리퀘 코드가 적용이 되질 않았으므로 시드내용을 수정해야합니다.

전부 완료되었다면 /captive 명령을 통해 활성 해주세요.

**Comment by thenist** [comment]
@brimstone07 또한 오류가 발생시 버킷 로그를 첨부하여 주십시오.

**Comment by brimstone07** [comment]
> 1.16.3 페이퍼 바로 [여기](https://papermc.io/api/v1/paper/1.16.3/latest/download)서 다운로드가 가능합니다.
> 또한 월드자체 시드를 불러오는 플리퀘 코드가 적용이 되질 않았으므로 시드내용이 있는 코드를 직접 수정해야합니다.
> 
> 전부 완료되었다면 /captive 명령을 통해 활성 해주세요.

어떻게 수정하면 될까요ㅜㅜ

**Comment by qogusdn1017** [comment]
[이 커밋]https://github.com/noonmaru/inv-captive/commit/ed570b103a6d681175e17419d7eac6d2790d7957() 참고 바랍니다. @brimstone07

**Comment by brimstone07** [comment]
> [이 커밋][ed570b1](https://github.com/noonmaru/inv-captive/commit/ed570b103a6d681175e17419d7eac6d2790d7957()) 참고 바랍니다. @brimstone07

404..

**Comment by brimstone07** [comment]
> @brimstone07 또한 오류가 발생시 버킷 로그를 첨부하여 주십시오.

아니 그냥 안되요

**Comment by thenist** [comment]
@brimstone07 안되니 버킷 시작부터 끝까지 전체로그를 첨부하라는 뜻입니다. logs폴더에서 latest.log를 첨부하면됩니다

**Comment by brimstone07** [comment]
[latest.log](https://github.com/noonmaru/inv-captive/files/5688945/latest.log)
로그 여깃습니다

**Comment by brimstone07** [comment]
> @brimstone07 우선 java가 구버전입니다 java가 구버전이라 kotlin플러그인이 작동하지 않네요 또한 plugins폴더에 plugin.jar가 잘못된거 같네요 제거하시고 테스트한 후 다시 로그 첨부하세요.

자바 싹다 지우고 자바 공식홈페이지에서 새것 다운받았습니다.
plugins.jar 지우고 다시 실행해도 안됩니다.. 일단 말씀대로 로그 첨부 하겠습니다.
[latest.log](https://github.com/noonmaru/inv-captive/files/5692136/latest.log)

**Comment by thenist** [comment]
@brimstone07 
kotlin 최신버전이 java 11을 요구하므로 https://github.com/noonmaru/kotlin-plugin/releases/download/1.4.20/Kotlin.jar를 받으십시오 java 8에서 마지막으로 동작하는 버전입니다 아직까지는 최신버전하고 다른점 없습니다.
 그리고 InvCaptive (2).jar는 지우세요 또한 gradle-wrapper.jar는 플러그인 아닙니다 지우세요
그리고 InvCaptive 플러그인이 잘못된걸 넣으신것 같습니다
여기 1.16.4 용으로 다시 빌드한 버전을 드리겠습니다 spigot도 1.16.4로 바꾸세요.
https://drive.google.com/file/d/12xzhiKa80MG4BBpDqKYeQvZTLVDGBLaZ/view?usp=sharing

**Comment by brimstone07** [comment]
> @brimstone07
> kotlin 최신버전이 java 11을 요구하므로 [https://github.com/noonmaru/kotlin-plugin/releases/download/1.4.20/Kotlin.jar를](https://github.com/noonmaru/kotlin-plugin/releases/download/1.4.20/Kotlin.jar%EB%A5%BC) 받으십시오 java 8에서 마지막으로 동작하는 버전입니다 아직까지는 최신버전하고 다른점 없습니다.
> gradle-wrapper.jar는 플러그인 아닙니다 지우세요
> 그리고 InvCaptive 플러그인이 잘못된걸 넣으신것 같습니다(InvCaptive.jar InvCaptive(2).jar 둘다 지우세요)
> 여기 1.16.4 용으로 다시 빌드한 버전을 드리겠습니다 spigot도 1.16.4로 바꾸세요.
> https://drive.google.com/file/d/12xzhiKa80MG4BBpDqKYeQvZTLVDGBLaZ/view?usp=sharing

죄송한데 그 윗쪽 자바 11 링크가 404인데요

**Comment by thenist** [comment]
> 
> 
> > @brimstone07
> > kotlin 최신버전이 java 11을 요구하므로 [https://github.com/noonmaru/kotlin-plugin/releases/download/1.4.20/Kotlin.jar를](https://github.com/noonmaru/kotlin-plugin/releases/download/1.4.20/Kotlin.jar%EB%A5%BC) 받으십시오 java 8에서 마지막으로 동작하는 버전입니다 아직까지는 최신버전하고 다른점 없습니다.
> > gradle-wrapper.jar는 플러그인 아닙니다 지우세요
> > 그리고 InvCaptive 플러그인이 잘못된걸 넣으신것 같습니다(InvCaptive.jar InvCaptive(2).jar 둘다 지우세요)
> > 여기 1.16.4 용으로 다시 빌드한 버전을 드리겠습니다 spigot도 1.16.4로 바꾸세요.
> > https://drive.google.com/file/d/12xzhiKa80MG4BBpDqKYeQvZTLVDGBLaZ/view?usp=sharing
> 
> 죄송한데 그 윗쪽 자바 11 링크가 404인데요
수정했습니다.

**Comment by qogusdn1017** [comment]
> [이 커밋](https://github.com/noonmaru/inv-captive/commit/ed570b103a6d681175e17419d7eac6d2790d7957) 참고 바랍니다. @brimstone07 

Currently Link Fixed.

**Comment by qogusdn1017** [comment]
혹여나 정상 작동할시 이슈 닫아주시면 감사하겠습니다 :)
