### ISSUE TITLE
어떻게 적용해요?

### ISSUE THREAD

**Issue by meDada1357** [noonmaru/inv-captive#17]
그 모든 플러그인을 다넣었는데도 적용이안됨니다 어떻게하죠?

**Comment by qogusdn1017** [comment]
작동되면 이슈 닫아주세요.

**Comment by qogusdn1017** [comment]
> /captive를 사용해도 되지않습니다 ㅠㅠ

혹시 정확히 어떻게 안되는지 알려주실수 있으신가요?

+ 의존성 플러그인들은 전부 넣으셨나요?

**Comment by thenist** [comment]
만약 설명이 어렵다면 logs폴더에 latest.log를 첨부하여 주십시오

**Comment by meDada1357** [comment]
모든 의존성 플러그인은 kotlin, Tap 넣었어요. 그리고 latest.log는 있긴한데 아무것도 안적혀있어요

**Comment by qogusdn1017** [comment]
> 모든 의존성 플러그인은 kotlin, Tap 넣었어요. 그리고 latest.log는 있긴한데 아무것도 안적혀있어요

서버를 한번 돌리시고 이후 나오는 latest.log 로그파일을 주실 수 있으실까요

**Comment by meDada1357** [comment]
[latest.log](https://github.com/noonmaru/inv-captive/files/5713374/latest.log) 이렇게 하면 된건가요?

**Comment by Mimoprty** [comment]
> [latest.log](https://github.com/noonmaru/inv-captive/files/5713374/latest.log) 이렇게 하면 된건가요?

서버 플러그인폴더에 InvCaptive, Kotlin.jar [https://github.com/noonmaru/kotlin-plugin/releases/tag/1.4.21](url) 그리고 ProtocolLib [https://github.com/dmulloy2/ProtocolLib/releases/download/4.5.1/ProtocolLib.jar](url) 만 넣어주시고 서버 한 번 돌려보세요

**Comment by qogusdn1017** [comment]
> [latest.log](https://github.com/noonmaru/inv-captive/files/5713374/latest.log) 이렇게 하면 된건가요?

자바 버전 몇인가요

**Comment by meDada1357** [comment]
무엇을 말씀하시는 잘모르겠네요

**Comment by thenist** [comment]
@meDada1357 
현재 자바 8을 사용하시는걸로 확인되었습니다.
kotlin 플러그인 1.4.21 버전은 자바 11이상만을 지원하므로 https://github.com/noonmaru/kotlin-plugin/releases/tag/1.4.20
여기에서 1.4.20 버전을 받아서 교체하여 주십시오.

**Comment by thenist** [comment]
@meDada1357 문제가 발생한경우 다시 latest.log를 첨부하여주시고 된다면 이슈를 받아주세요.
