### ISSUE TITLE
seed 변경 오류

### ISSUE THREAD

**Issue by koname2da** [noonmaru/inv-captive#18]
java bytecode editor로 seed를 바꾸려고 하는데 오류가 뜹니다
Error: Argument type error at line 74, instruction "ldc"
2번 이슈 읽어봤는데 이해도 잘 안 되네요

**Comment by qogusdn1017** [comment]
현재 코드를 Clone해서 빌드하시면 아마 지동으로 시드 불러와질겁니다

**Comment by koname2da** [comment]
자세한 방법을 알려주시면 감사하겠습니다

**Comment by qogusdn1017** [comment]
> 자세한 방법을 알려주시면 감사하겠습니다

#19 참고.

**Comment by koname2da** [comment]
OpenJDK를 다운로드하고 JAVA_HOME을 설정 한 후 빌드시도 했더니 에러가 떴습니다

.₩gradlew : '.₩gradlew' 용어가 cmdlet, 함수, 스크립트 파일 또는 실행할 수 있는 프로그램 이름으로 인식되지 않습니다. 이
름이 정확한지 확인하고 경로가 포함된 경우 경로가 올바른지 검증한 다음 다시 시도하십시오.
위치 줄:1 문자:1
+ .₩gradlew clean shadowJar
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.₩gradlew:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by koname2da** [comment]
위 방법대로 해 보았는데 빌드 실패가 떴습니다
> Configure project :
relocate = true

> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find org.spigotmc:spigot:1.16.4-R0.1-SNAPSHOT.
     Searched in the following locations:
       - file:/C:/Users/kimsy/.m2/repository/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/kimsy/.m2/repository/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
       - https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
       - https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
       - https://jitpack.io/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 51s
2 actionable tasks: 1 executed, 1 up-to-date
PS C:\Users\kimsy\Desktop\inv-captive-master\inv-captive-master>

**Comment by qogusdn1017** [comment]
> 위 방법대로 해 보았는데 빌드 실패가 떴습니다
> 
> > Configure project :
> > relocate = true
> 
> > Task :compileKotlin FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':compileKotlin'.
> 
> > Could not resolve all files for configuration ':compileClasspath'.
> > Could not find org.spigotmc:spigot:1.16.4-R0.1-SNAPSHOT.
> > Searched in the following locations:
> > - file:/C:/Users/kimsy/.m2/repository/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
> > - file:/C:/Users/kimsy/.m2/repository/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
> > - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
> > - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
> > - https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
> > - https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
> > - https://jitpack.io/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
> > - https://jitpack.io/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
> > Required by:
> > project :
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 51s
> 2 actionable tasks: 1 executed, 1 up-to-date
> PS C:\Users\kimsy\Desktop\inv-captive-master\inv-captive-master>

아 이 오류 뜨는지 안뜨는지 헷갈려했는데 결국 뜨네요

## BuildTools

> [빌드툴즈](https://www.spigotmc.org/wiki/buildtools/) 한번 돌리시면 해결될겁니다.
새 폴더를 만들고 그 안에 바로 넣으시는걸 권장합니다.
똑같이 그 폴더 내에서 cmd나 Powershell을 열어
`java -jar BuildTools.jar --rev 1.16.4`를 쳐주세요.

## 다 끝났으면 뭘 해야하나요?

> 끝나면 다시 빌드하심 될겁니다.
빌드하신 후 소스코드 다운 받은 폴더내에 있는 build -> libs -> inv-captive 플러그인을 서버의 Plugins 폴더에 넣어주세요.
Paper 1.16.4에서 작동됩니다.
서버 구동 후 plugin.yml을 수정해야되는거로 알고 있습니다.

**Comment by koname2da** [comment]
빌드 도중 오류가 나네요
> Configure project :
relocate = true

> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve org.spigotmc:spigot:1.16.4-R0.1-SNAPSHOT.
     Required by:
         project :
      > Could not resolve org.spigotmc:spigot:1.16.4-R0.1-SNAPSHOT.
         > Unable to load Maven meta-data from https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml.
            > Could not get resource 'https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml'.
               > Could not GET 'https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml'.
                  > Received fatal alert: handshake_failure

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
2 actionable tasks: 1 executed, 1 up-to-date

**Comment by qogusdn1017** [comment]
> 빌드 도중 오류가 나네요
> 
> > Configure project :
> > relocate = true
> 
> > Task :compileKotlin FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':compileKotlin'.
> 
> > Could not resolve all files for configuration ':compileClasspath'.
> > Could not resolve org.spigotmc:spigot:1.16.4-R0.1-SNAPSHOT.
> > Required by:
> > project :
> > > Could not resolve org.spigotmc:spigot:1.16.4-R0.1-SNAPSHOT.
> > > Unable to load Maven meta-data from https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml.
> > > Could not get resource 'https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml'.
> > > Could not GET 'https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml'.
> > > Received fatal alert: handshake_failure
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 14s
> 2 actionable tasks: 1 executed, 1 up-to-date

BuildTools 돌리신거 확실한가요?

**Comment by qogusdn1017** [comment]
@koname2da 
build.gradle.kts 하단 부분에서
```kotlin
for (v in listOf("1.16.3")) {
```
를 찾아
```kotlin
for (v in listOf("1.16.4")) {
```
로 바꾸신후

PowerShell에서 `.\gradlew setupWorkspace`를 쳐보시겠어요?

그러면 해결될거 같습니다.

**Comment by koname2da** [comment]
오 빌드 성공했습니다 정말 감사드립니다
