### ISSUE TITLE
잠금해제 아이템 변경

### ISSUE THREAD

**Issue by BABSANG4273** [noonmaru/inv-captive#19]
잠금 해제하는 아이템을 바꿀수 있나요? 혹시 몰라서 하나 해보니까 방송에 나온거랑 똑같아서..

**Comment by qogusdn1017** [comment]
현재 Releases에 있는게 아닌 최신코드를 Clone해서 빌드하시면 됩니다.

**Comment by BABSANG4273** [comment]
잘 모르겠습니다...

**Comment by qogusdn1017** [comment]
@BABSANG4273 

최대한 쉽게 설명해드리겠습니다.

## 빌드방법 :

1. [현재 Clone 가능한 소스](https://github.com/noonmaru/inv-captive/archive/master.zip)입니다. 이를 다운하시고 압축을 풀어주세요.

2. 압축을 푼 폴더 내에서 Shift + 우클릭을 하여 PowerShell을 열어주세요.

3. `.₩gradlew clean shadowJar` 명령을 사용해 빌드하세요.

## 문제 발생시

- JDK를 설치하시고 JAVA_HOME을 설정해주세요. 이는 구글에 검색하시면 상세한 내용이 많습니다. 개인적으로는 OpenJDK 8 또는 11을 설치하는걸 권장합니다.

- 이외의 문제 상황이 있으면 댓글 달아주세요.

**Comment by BABSANG4273** [comment]
![20201223_142856](https://user-images.githubusercontent.com/70741102/102963007-65471680-452b-11eb-8bf3-3d450cc30b08.png)
이렇게 하는거 아닌가요? 그리고 이거 되면 원래 있던 invcaptive파일은 지워야하나요

**Comment by qogusdn1017** [comment]
> ![20201223_142856](https://user-images.githubusercontent.com/70741102/102963007-65471680-452b-11eb-8bf3-3d450cc30b08.png)
> 이렇게 하는거 아닌가요? 그리고 이거 되면 원래 있던 invcaptive파일은 지워야하나요

원래 `.\gradlew clean shadowJar`를 입력하면 정상적으로 작동해야하는데... 파일이 없다고 오류가 뜨네요

혹시 내부에 파일은 정상인지 확인 부탁드립니다. 저는 잘 되었거든요.

![image](https://user-images.githubusercontent.com/36562850/102969063-6468b180-4538-11eb-886e-cebe85e37412.png)

(현재 이미지에 나와 있는 명령은 신경 쓰지 마세요. 빌드 도중 필요 파일이 없어서 빌드툴즈 돌리고 있습니다.)

**Comment by sgkill6** [comment]
PS E:\다운로드\inv-captive-master (2)\inv-captive-master> .\gradlew clean shadowJar

> Configure project :
relocate = true

> Task :compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find org.spigotmc:spigot:1.16.4-R0.1-SNAPSHOT.
     Searched in the following locations:
       - file:/C:/Users/sgkil/.m2/repository/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/sgkil/.m2/repository/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
       - https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
       - https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
       - https://jitpack.io/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/org/spigotmc/spigot/1.16.4-R0.1-SNAPSHOT/spigot-1.16.4-R0.1-SNAPSHOT.pom
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
2 actionable tasks: 1 executed, 1 up-to-date
PS E:\다운로드\inv-captive-master (2)\inv-captive-master>

**Comment by sgkill6** [comment]
이거 왜이런 건가요?

**Comment by alsrjs0725** [comment]
> > ![20201223_142856](https://user-images.githubusercontent.com/70741102/102963007-65471680-452b-11eb-8bf3-3d450cc30b08.png)
> > 이렇게 하는거 아닌가요? 그리고 이거 되면 원래 있던 invcaptive파일은 지워야하나요
> 
> 원래 `.\gradlew clean shadowJar`를 입력하면 정상적으로 작동해야하는데... 파일이 없다고 오류가 뜨네요
> 
> 혹시 내부에 파일은 정상인지 확인 부탁드립니다. 저는 잘 되었거든요.
> 
> ![image](https://user-images.githubusercontent.com/36562850/102969063-6468b180-4538-11eb-886e-cebe85e37412.png)
> 
> (현재 이미지에 나와 있는 명령은 신경 쓰지 마세요. 빌드 도중 필요 파일이 없어서 빌드툴즈 돌리고 있습니다.)

저 문제 자체는 JDK를 다운받으면 해결됩니다만 다운받고 명령어를 입력하니 아래와 같은 오류가 나오네요
![image](https://user-images.githubusercontent.com/74909540/103059896-bcabbc00-45e9-11eb-8ba3-34ecf41450d6.png)

**Comment by qogusdn1017** [comment]
> > > ![20201223_142856](https://user-images.githubusercontent.com/70741102/102963007-65471680-452b-11eb-8bf3-3d450cc30b08.png)
> > > 이렇게 하는거 아닌가요? 그리고 이거 되면 원래 있던 invcaptive파일은 지워야하나요
> > 
> > 
> > 원래 `.\gradlew clean shadowJar`를 입력하면 정상적으로 작동해야하는데... 파일이 없다고 오류가 뜨네요
> > 혹시 내부에 파일은 정상인지 확인 부탁드립니다. 저는 잘 되었거든요.
> > ![image](https://user-images.githubusercontent.com/36562850/102969063-6468b180-4538-11eb-886e-cebe85e37412.png)
> > (현재 이미지에 나와 있는 명령은 신경 쓰지 마세요. 빌드 도중 필요 파일이 없어서 빌드툴즈 돌리고 있습니다.)
> 
> 저 문제 자체는 JDK를 다운받으면 해결됩니다만 다운받고 명령어를 입력하니 아래와 같은 오류가 나오네요
> ![image](https://user-images.githubusercontent.com/74909540/103059896-bcabbc00-45e9-11eb-8ba3-34ecf41450d6.png)

Kotlin 업데이트 하셔야 할듯한데...

**Comment by noonmaru** [comment]
최신버전으로 실행하세요.
plugin/InvCaptive/config.yml에 seed를 변경하시면 됩니다.
