### ISSUE TITLE
블럭 해금 아이템 고정 오류

### ISSUE THREAD

**Issue by skyyun16** [noonmaru/inv-captive#2]
플러그인 실행시 random seed에 의해 해금되는 인벤토리의 블럭이 달라지는 것이 아닌,  seed를 바꾸더라도 같은 아이템으로만(유튜브 영상에 나온 블록들 ex. 참나무 묘목, 흰색 침대, 흰색 카펫, 종 등) 인벤토리가 해금됩니다. 

사용 플러그인
- Paper version git-Paper-192
- Kotlin

**Comment by skyyun16** [comment]
그게 아니라 플러그인 작동 시키고 나서 인벤토리를 해금시킬수 있는 블럭이 시드에 따라 달라지지를 않는거를 말하는 거에요

**Comment by noonmaru** [comment]
값을 크게변경해보세요

마인크래프트의 seed가 아닌 InvCaptivePlugin 내의 seed를 변경해야합니다.

**Comment by skyyun16** [comment]
Java Bytecode Editor로 InvCaptivePlugin 내의 seed를 변경하려니 자꾸 

Error : Argument type error at line 74, instruction "ldc"

라고 오류가 뜨네요
혹시 방송을 보신분들을 위해서 seed를 수정한 버전을 올려줬으면 하는 바람입니다...
답변 감사합니다!

**Comment by qogusdn1017** [comment]
[이 커밋](https://github.com/noonmaru/inv-captive/commit/ed570b103a6d681175e17419d7eac6d2790d7957)을 확인해 보시면 금방 이해될겁니다.

저도 값을 변경하니 인벤토리 해금 블럭들이 달라졌습니다.

**Comment by skyyun16** [comment]
감사합니다 참고하겠습니다!

**Comment by devil0414** [comment]
이제 이슈 닫아도 되지 않을까요?
