### ISSUE TITLE
Seed 폴더 없음

### ISSUE THREAD

**Issue by AvadaKedavra1020** [noonmaru/inv-captive#27]
그 seed 변경을 하고싶은데. 그 InCaptive 폴더 안에 config.yml이 없어요. 거기 inventory.yml밖에 없어요. 제가 다운을 다른거를 했나요?

**Comment by ghost** [comment]
src₩main₩resources 의 config.yml을 변경해야합니다.

~~이제 확실히 알았네요 plugins 디렉터리에 생성 안된다는걸~~

변경 후 빌드하시면 될듯합니다

**Comment by noonmaru** [comment]
최신 버전으로 실행해보세요
아래 링크의 파일을 다운로드하여 powershell로 실행시키면 스스로 실행가능한 서버를 구축합니다.

https://github.com/noonmaru/inv-captive/releases/download/0.2.0/inv-captive.ps1

자바 11 버전의 실행환경이 필요합니다.
