### ISSUE TITLE
Could not load 'plugins\InvCaptive.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by ghost** [noonmaru/inv-captive#28]

**Comment by ghost** [comment]
플러그인을 실행하고 리로드 하면 위와 같은 오류가 뜹니다.

**Comment by noaoa** [comment]
Could not load 'plugins\Kotlin.jar' in folder 'plugins' 위 오류도 덤으로 같이 뜸니다

**Comment by noonmaru** [comment]
최신 버전으로 실행해보세요
아래 링크의 파일을 다운로드하여 powershell로 실행시키면 스스로 실행가능한 서버를 구축합니다.

https://github.com/noonmaru/inv-captive/releases/download/0.2.0/inv-captive.ps1

자바 11 버전의 실행환경이 필요합니다.
