### ISSUE TITLE
플러그인 빌드 관련 문제

### ISSUE THREAD

**Issue by Mainsystenn** [noonmaru/inv-captive#29]
내부의 시드를 바꾸는거까지는 했는데 빌드에서 막혔습니다.
파워셀로도 시도해보고 알집 압축하는것도 시도해보고 7zip으로 jar 파일 압축을 시도해보긴했는데 뭔가 잘못했는지 플러그인에 안뜨더라구요..
어떻게 해야할까요?

**Comment by noonmaru** [comment]
최신 버전으로 실행해보세요
아래 링크의 파일을 다운로드하여 powershell로 실행시키면 스스로 실행가능한 서버를 구축합니다.

https://github.com/noonmaru/inv-captive/releases/download/0.2.0/inv-captive.ps1

자바 11 버전의 실행환경이 필요합니다.

**Comment by AvadaKedavra1020** [comment]
Powershell로 하긴했는데 Updating paper.jar from https://papermc.io/api/v1/paper/1.16.4/latest/download
이게 떠요. 달라진것도 없고요.

**Comment by Mainsystenn** [comment]
파워셀 켜서 ./gradlew build 라고 치니까 

Task :compileKotlin FAILED

FAILURE: Build failed with an exception

* What went wrong:
Execution failed for task ' :compileKotlin',
>Could not resolve all files for configuration ' :compileClasspath',
>Could not find org. spigotmc : spigot :1.16.4-RO.1-SNAPSHOT

라고 뜨면서 아래쪽에 빌드 실패 라고도 뜨네요

**Comment by Mainsystenn** [comment]
아 저게 서버구축하는거였군요 
감사합니다...

**Comment by chipppppp** [comment]
> 파워 셀 켜서 ./gradlew build라고 치니까
> 
> 작업 : compileKotlin FAILED
> 
> 실패 : 예외로 인해 빌드 실패
> 
> * 잘못된 점 : 
>   ': compileKotlin'작업에 대한 실행 실패,
> 
> > 구성 ': compileClasspath'에 대한 모든 파일을 
> > 확인할 수 없습니다. 조직을 찾을 수 없습니다. spigotmc : 스피 곳 : 1.16.4-RO.1-SNAPSHOT
> 
> 라고 뜨면서 낮에 빌드 실패라고도 뜨 네요

저도 저렇게뜨는데 어떻게 해야하는지 아시나요
