### ISSUE TITLE
Seed 변경안됨

### ISSUE THREAD

**Issue by AvadaKedavra1020** [noonmaru/inv-captive#30]
제가 그 매모장에 뭐 seed: -8109248019 어쩌고 저쩌고 있어서 그거를 바꿨는데. 아이템 다 똑같아요. 이거 신규버전인데 진짜 몇번을 켰다 끈지 몰르겠어요. 뭐가 문제이죠?

**Comment by ghost** [comment]
메모장 수정하셨으면 다시 서버를 여시거나 reload 명령어 실행해보세요

**Comment by AvadaKedavra1020** [comment]
안되는뎁.
