### ISSUE TITLE
버그를 찾았습니다..

### ISSUE THREAD

**Issue by Mainsystenn** [noonmaru/inv-captive#31]
최근 불편한동거를 플레이하던 도중 아이템액자에 블럭을 설치하려고 휠을 돌리다가 실수로 방벽이 든손으로 우클릭을 했는데 그 방벽이 아이템액자에 설치가 되고 그 방벽이 있던 칸은 방벽이사라져 없는 상태가 되었습니다.

![2021-01-09_22.58.54-1.png](https://user-images.githubusercontent.com/77065694/104093611-e42fa380-52ce-11eb-8782-237140284b8e.png)

**Comment by noonmaru** [comment]
엌

**Comment by Mainsystenn** [comment]
> 엌

주말이라 힘드실텐데.. 화이팅....
