### ISSUE TITLE
Seed 바꾸는 법 제발 좀 알려주세요 ㅠㅠㅠ

### ISSUE THREAD

**Issue by AvadaKedavra1020** [noonmaru/inv-captive#36]
제가 진짜 이거 이슈들 많이 봤는데 진짜 다 안되는거 같아요. 아니 분명히 똑같이 한것같은데 제발 좀 알려주세요.

**Comment by sonogram10** [comment]
에러 사항을 말해주세요

**Comment by AvadaKedavra1020** [comment]
일단 진짜 그냥 seed를 변경하고 플레이했는데 다 똑같은거에요. 정확히 무슨 폴더의 있는지 좀 알려주세요. 그리고 뭘 바꿔야되는지.

**Comment by ghost** [comment]
마인크래프트 맵에 있는 시드 말씀하시는거죠? 플러그인 시드가 아니라

**Comment by AvadaKedavra1020** [comment]
아 플러그인 시드 말하는거에요 그 인벤토리 시드.

**Comment by ghost** [comment]
답변이 늦어져서 죄송합니다.
플러그인 폴더를 열면 InvCaptive 폴더 안에 config.yml에서 바꾸신거 맞나요?

만약 yml 없으시다면 무슨 플러그인들을 넣으셨는지 말씀해주세요

**Comment by AvadaKedavra1020** [comment]
아니 config.yml은 있어요 근데 그거를 바꿨는데 인벤토리 헤제 아이템들이 똑같아요.

**Comment by sonogram10** [comment]
어떻게 바꿨는지 보여주세요.

**Comment by AvadaKedavra1020** [comment]
seed: 24613095871
이거 시드가 다른거였는데 바꿨어요 
이거 아니에요?

**Comment by ghost** [comment]
시드를 크게 바꿔보세요 그럼 될꺼예요

**Comment by AvadaKedavra1020** [comment]
무슨 뜻? 크게 바꿔보라는거 그냥 시드를 엄청 많은 숫자로? 죄송해요 무슨 뜻인지 몰르겠어요.

**Comment by Minoprty** [comment]
> 무슨 뜻? 크게 바꿔보라는거 그냥 시드를 엄청 많은 숫자로? 죄송해요 무슨 뜻인지 몰르겠어요.

자릿수 많은 숫자로 변경해보세요. 전 18자릿수 만큼 했네요

**Comment by AvadaKedavra1020** [comment]
113028571823957198237590817346980734986713908751982376893147986473986793187592301875394186793481659837630498612348960 어....이정도에 숫자로 바꿨는데...안되는데욥.

**Comment by AvadaKedavra1020** [comment]
뭐 어떤 명령어로 다 시드를 바꿔야되냐요?

**Comment by Minoprty** [comment]
정확히 /invcaptive 명령어가 안되는 건가요 아니면 명령어는 잘 작동하는데 해금하는 아이템이 다 똑같은 건가요?

**Comment by sonogram10** [comment]
플러그인 내의 시드를 바꾼 건가요?

**Comment by AvadaKedavra1020** [comment]
그런것같은데...

**Comment by ghost** [comment]
> 113028571823957198237590817346980734986713908751982376893147986473986793187592301875394186793481659837630498612348960 어....이정도에 숫자로 바꿨는데...안되는데욥.

그정도로 바꿀 필요는 애초에 없는데

**Comment by ghost** [comment]
- 서버는 무슨버전으로 열었고, 어떻게 구동했나요?

- 서버 콘솔에 오류가 났나요? (Java 11 업데이트 안내 제외)

- 플러그인은 정확히 무엇이 들어갔나요?

이 내용을 **자세히** 구술 부탁드립니다.

**Comment by Minoprty** [comment]
> > 무슨 뜻? 크게 바꿔보라는거 그냥 시드를 엄청 많은 숫자로? 죄송해요 무슨 뜻인지 몰르겠어요.
> 
> 자릿수 많은 숫자로 변경해보세요. 전 18자릿수 만큼 했네요

아 이거 자릿수는 상관 없네요.

**Comment by AvadaKedavra1020** [comment]
> * 서버는 무슨버전으로 열었고, 어떻게 구동했나요?
> * 서버 콘솔에 오류가 났나요? (Java 11 업데이트 안내 제외)
> * 플러그인은 정확히 무엇이 들어갔나요?
> 
> 이 내용을 **자세히** 구술 부탁드립니다.

1.16.3 버전 페이퍼를 썻습니다. 
java 11을 다운해서 쓰고
플러그인은 ProtocolLib.jar, Kotlin.jar, InvCaptive.jar, inv-captive.ps1, ProtocolLib, inv-captive-master, InvCaptive, bStats, 
.inv-captive, 이것들을 사용하고있습니다.

**Comment by ghost** [comment]
> > * 서버는 무슨버전으로 열었고, 어떻게 구동했나요?
> > * 서버 콘솔에 오류가 났나요? (Java 11 업데이트 안내 제외)
> > * 플러그인은 정확히 무엇이 들어갔나요?
> > 
> > 이 내용을 **자세히** 구술 부탁드립니다.
> 
> 1.16.3 버전 페이퍼를 썻습니다.
> java 11을 다운해서 쓰고
> 플러그인은 ProtocolLib.jar, Kotlin.jar, InvCaptive.jar, inv-captive.ps1, ProtocolLib, inv-captive-master, InvCaptive, bStats,
> .inv-captive, 이것들을 사용하고있습니다.

플러그인 목록내에서 .jar를 물어본 것이었습니다. .jar과 플러그인 이름이 적힌 폴더를 제외하고 나머지 필요없는 파일이 있을 경우 지워주시길 바라겠습니다.

혹은 inv-captive.ps1을 실행 해주세요. ~~사실 inv-captive.ps1이 빠르고 돌리면 훨씬 더 속편한~~

**Comment by AvadaKedavra1020** [comment]
inv-captive.ps1으로 실행했는데 1.16.4로 하라고 되있어서 했는데 captive 명령어가 안돼요.

**Comment by AvadaKedavra1020** [comment]
여려분 진짜 감사합니다 op 주고 다 됐어요!!! 진짜 너무하고 싶었어요! 
이제라도 할수있어서 좋네요 
여려분 진짜 진짜 정말 감사합니다.

**Comment by ghost** [comment]
해결되었다면 이슈 닫아주시길 바랍니다.
