### ISSUE TITLE
명령어를 사용하면 오류가뜹니다

### ISSUE THREAD

**Issue by HGNB0508** [noonmaru/inv-captive#38]
![1611631910581](https://user-images.githubusercontent.com/78014392/105815656-9e751980-5ff6-11eb-8484-974147cff153.jpg)
명령어를 치면 일이렇게 나옵니다  플러그인은 코틀린,포로토콜 립,동거 플러그인
![1611633527106](https://user-images.githubusercontent.com/78014392/105815804-d0867b80-5ff6-11eb-9e13-3395d847ed55.jpg)

**Comment by ghost** [comment]
Paper 1.16.4~1.16.5 중 하나로 서버를 열어주시길 바랍니다.

아래는 페이퍼 1.16.5를 바로 다운해주는 링크입니다.

https://papermc.io/api/v1/paper/1.16.5/latest/download

**Comment by HGNB0508** [comment]
페이퍼 1.16.5로 해봐도 똑같습니다  지금 invcaptive,Kotlin,protocollib만 적용해 놨는데 이것만 적용 하는게 맞나요?

**Comment by HGNB0508** [comment]
1.16.3으로 하니 정상작동 하네요

**Comment by ghost** [comment]
아 최신버전이 아닌가보구나
