### ISSUE TITLE
seed 바꾸는 방법좀 알려주세요ㅠㅠ

### ISSUE THREAD

**Issue by bigmo13** [noonmaru/inv-captive#39]
최근 InvCaptive소스 코드에 config.yml있다는데 저는 없는데 어떻게 해요?

**Comment by ghost** [comment]
최신소스코드에서 바꾸거나

jar 넣고 시드 바꾸거나

[릴리즈](https://github.com/noonmaru/releases)에 있는 ps1파일을 파워셸로 실행한뒤 플러그인 폴더에서 찾던가...

**시도를 해보셨는지...**

**Comment by bigmo13** [comment]
혹시 최신소스코드가 https://github.com/noonmaru/inv-captive/releases/tag/0.2.0 안에있는 소스코드요?
안니라면 링크좀 주실 수 있나요?

**Comment by ghost** [comment]
> 혹시 최신소스코드가 https://github.com/noonmaru/inv-captive/releases/tag/0.2.0 안에있는 소스코드요?
> 안니라면 링크좀 주실 수 있나요?

PowerShell에서 [inv-captive.ps1](https://github.com/noonmaru/inv-captive/releases/download/0.2.0/inv-captive.ps1) 실행 바랍니다.

실행환경 확인하시고요.

**Comment by bigmo13** [comment]
> > 혹시 최신 소스 코드가 https://github.com/noonmaru/inv-captive/releases/tag/0.2.0 안에있는 소스 코드 요? 
> > 안니라면 링크 좀 주실 수 있나요?
> 
> PowerShell에서 [inv-captive.ps1 실행 바랍니다](https://github.com/noonmaru/inv-captive/releases/download/0.2.0/inv-captive.ps1) .
> 
> 실행 환경 확인 하시고요.

어떻게하시는지 알려주실수있나요?

**Comment by bigmo13** [comment]
아 감사합니다

**Comment by ghost** [comment]
해결되셨다면 이슈 닫아주세요.

**Comment by flwntgh** [comment]
닫혀있는것도 찾아가면서 해봤는데 되지가 않습니다
이해도 안되고요 너무 하고싶은데 하지를 못하네요
/captive 명령어를 쳐도 실행이안되요

**Comment by ghost** [comment]
> 닫혀있는것도 찾아가면서 해봤는데 되지가 않습니다
> 이해도 안되고요 너무 하고싶은데 하지를 못하네요
> /captive 명령어를 쳐도 실행이안되요

관련되어서는 기존의 이슈를 닫고 새 이슈를 만드시던지, 기존 이슈를 업데이트 시켜주시길 바랍니다.

**우선적으로 시도하시고 질문하십시오. 이슈는 질문게시판이 아니라는 점은 감안해주셨으면 합니다.**

**Comment by Oysfgaq** [comment]
> 닫혀있는것도 찾아가면서 해봤는데 되지가 않습니다
> 이해도 안되고요 너무 하고싶은데 하지를 못하네요
> /captive 명령어를 쳐도 실행이안되요

0.2.0은 /invcaptive 로 실행해요
/invcaptive로 해보세요
