### ISSUE TITLE
inv-captive.ps1 오류

### ISSUE THREAD

**Issue by wkdgur** [noonmaru/inv-captive#42]
Inv-captive.ps1을 실행해보니
Downloading paper.jar from https://papermc.io/api/v1/paper/1.16.4/latest/download
Downloading Kotlin.jar from https://github.com/noonmaru/kotlin-plugin/releases/download/1.4.21/Kotlin.jar
Downloading AutoReloader.jar from https://github.com/noonmaru/auto-reloader/releases/download/1.0.2/AutoReloader.jar
Downloading InvCaptive.jar from https://github.com/noonmaru/inv-captive/releases/download/0.2.0/InvCaptive.jar
Downloading ProtocolLib.jar from https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/target/ProtocolLib.jar
Invalid maximum heap size: -Xmx4G
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Skip the backup? [Y]es, [N]o
N
7z : '7z' 용어가 cmdlet, 함수, 스크립트 파일 또는 실행할 수 있는 프로그램 이름으로 인식되지 않습니다. 이름이 정확한지
확인하고 경로가 포함된 경우 경로가 올바른지 검증한 다음 다시 시도하십시오.
위치 C:\Users\xxx\Desktop\inv-captive.ps1:163 문자:5
+     7z a -tzip $ArchiveName ./ "-xr!*.gz" "-x!paper.jar" "-x!paper.ps ...
+     ~~
    + CategoryInfo          : ObjectNotFound: (7z:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Backup completed backup/2021-01-28 192311.zip
Restart? [Y]es [N]o

이렇게 오류가 뜹니다

**Comment by thenist** [comment]
7zip을 설치하여 주세요

**Comment by ghost** [comment]
추가로 자바 재설치 바랍니다.
11버전이 현재 권장됩니다.

**Comment by wkdgur** [comment]
7zip을 설치해도 자바 11을 다시 설치해도 똑같습니다

**Comment by ghost** [comment]
> 7zip을 설치해도 자바 11을 다시 설치해도 똑같습니다

위쪽과 **완전히** 똑같은 오류인가요 아니면 다른 오류인가요?

64비트쪽 자바로 설치가 되었다면 정상이여야 할듯한데

**Comment by wkdgur** [comment]
64bit java설치 후에도 같은멘트가 뜨네요

**Comment by wkdgur** [comment]
컴퓨터 초기화하니 되네요
