### ISSUE TITLE
빌드 실패

### ISSUE THREAD

**Issue by chipppppp** [noonmaru/inv-captive#45]
cmd 에서 cd 파일경로 > gradlew.bat build 라고 쳤는데 

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\wlsdb\Desktop\inv-captive-master\build.gradle.kts' line: 105

* What went wrong:
Script compilation errors:

  Line 105:                         standardOutput = OutputStream.nullOutputStream()
                                                                  ^ Unresolved reference: nullOutputStream

  Line 106:                         errorOutput = OutputStream.nullOutputStream()
                                                               ^ Unresolved reference: nullOutputStream

2 errors

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
* 이렇게 나오는데 해결방법좀 알려주실분 있나요

**Comment by sonogram10** [comment]
gradlew.bat build 대신 gradlew buils를 쳐보세요

**Comment by chipppppp** [comment]
> gradlew.bat build 대신 gradlew build를 쳐보세요

'gradlew'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다. 라고 뜨네요;;

**Comment by chipppppp** [comment]
> gradlew build
> Task :compileKotlin FAILED
FAILURE: Build failed with an exception.
* Get more help at https://help.gradle.org
* What went wrong:
Execution failed for task ':compileKotlin'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find org.spigotmc:spigot:1.16.5-R0.1-SNAPSHOT.
     Searched in the following locations:f :compileClasspath > spigot-1.16.5-R0.1-SNAPSHOT.pom
       - file:/C:/Users/wlsdb/.m2/repository/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/maven-metadata.xml
       - file:/C:/Users/wlsdb/.m2/repository/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/spigot-1.16.5-R0.1-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/spigot-1.16.5-R0.1-SNAPSHOT.pom
       - https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/maven-metadata.xml
       - https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/spigot-1.16.5-R0.1-SNAPSHOT.pom
       - https://jitpack.io/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/org/spigotmc/spigot/1.16.5-R0.1-SNAPSHOT/spigot-1.16.5-R0.1-SNAPSHOT.pom
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
1 actionable task: 1 executed 라고 뜨네요

**Comment by thenist** [comment]
Buildtools.jar를 받아 Spigot 1.16.5를 먼저 빌드한후 실행하여 주세요.

**Comment by chipppppp** [comment]
> Buildtools.jar를 받아 Spigot 1.16.5를 먼저 빌드 한 후 실행하여주세요.

Buildtools.jar가 뭐죠 그리고 spigot1.16.5 빌드는 어떻게 하나요;;

**Comment by thenist** [comment]
@chipppppp
물어보기전 먼저 검색부터 합시다.
https://github.com/git-for-windows/git/releases/download/v2.30.1.windows.1/Git-2.30.1-64-bit.exe
이걸 받아 설치하고
https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
이걸 받은 다음 적당하게 새 폴더를 생성하여 buildtools.jar를 안에 넣고 
폴더의 빈자리를 우클릭하여 Git Bash Here를 선택하여 git bash를 연다음
java -jar Buildtools.jar --rev 1.16.5 를 실행하고 기다리면 빌드가 완료됩니다.

**Comment by chipppppp** [comment]
> @chipppppp
> 물어보기 전 먼저 검색부터합시다.
> https://github.com/git-for-windows/git/releases/download/v2.30.1.windows.1/Git-2.30.1-64-bit.exe
> 이걸 받아 설치하고
> [https : //hub.spigotmc .org / jenkins / job / BuildTools / lastSuccessfulBuild / artifact / target / BuildTools.jar 이걸](https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar)
> 받은 다음 적당하게 새 폴더를 생성하여 buildtools.jar를 안에
> 폴더의 빈자리를 우클릭하여 Git Bash Here를 선택하여 git bash를 연 다음
> java -jar Buildtools.jar --rev 1.16.5를 실행하고 기다리면 빌드가 완료됩니다.

저거 아무것도 몰라서 그런데 혹시 java -jar Buildtools.jar --rev 1.16.5가 뭔지 알수있을까요

**Comment by ghost** [comment]
그냥 릴리즈에서 ps1파일 받고 실행...

**Comment by ghost** [comment]
> > @chipppppp
> > 물어보기 전 먼저 검색부터합시다.
> > https://github.com/git-for-windows/git/releases/download/v2.30.1.windows.1/Git-2.30.1-64-bit.exe
> > 이걸 받아 설치하고
> > [https : //hub.spigotmc .org / jenkins / job / BuildTools / lastSuccessfulBuild / artifact / target / BuildTools.jar 이걸](https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar)
> > 받은 다음 적당하게 새 폴더를 생성하여 buildtools.jar를 안에
> > 폴더의 빈자리를 우클릭하여 Git Bash Here를 선택하여 git bash를 연 다음
> > java -jar Buildtools.jar --rev 1.16.5를 실행하고 기다리면 빌드가 완료됩니다.
> 
> 저거 아무것도 몰라서 그런데 혹시 java -jar Buildtools.jar --rev 1.16.5가 뭔지 알수있을까요

문제 해결되었다면 이슈닫아주시고, 아닐경우 이를 따라주세요:

## BuildTools 실행

**새 폴더를 만들고 그 안에서 BuildTools.jar를 실행하는걸 권장합니다.**

BuildTools.jar가 있는 디렉터리로 cmd를 이용해 이동시키거나 그 디렉터리 내에서 Shift + 우클릭을 누른 뒤 PowerShell을 켜서

`java -jar BuildTools.jar --rev 1.16.5` 명령을 입력합니다.

대부분의 서버 관리자들은 BuildTools를 이용해 Spigot을 받으려는 작업을 하지만, 개발자들은 로컬 메이븐 저장소에 Spigot관련 파일을 넣기 위해 사용하는 경우가 있습니다.

BuildTools 작업이 마쳐지면 `gradlew build`를 재시도 해보세요.

#### 여담

이 댓글에 잘못된 정보가 달려있거나 개선할점 등이 있다면 언제든 맨션하여 알려주시면 감사하겠습니다.

질문 작성자 분께: 제가 하기에는 좀 무례한 충고 일 수 있으나, 무조건 `작동 되지 않는다` 라 이야기하지 마시고, 검색을 시도해보세요.

**Comment by chipppppp** [comment]
> > > @chipppppp 
> > > 물어보기 전 먼저 검색부터합시다. 
> > > https://github.com/git-for-windows/git/releases/download/v2.30.1.windows.1/Git-2.30.1-64-bit.exe 
> > > 이걸 받아 설치하고 
> > > [https : //hub.spigotmc .org / jenkins / job / BuildTools / lastSuccessfulBuild / artifact / target / BuildTools.jar 이걸](https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar) 
> > > 받은 다음 적당하게 새 폴더를하여 buildtools.jar를 
> > > 폴더의 빈자리를 우클릭하여 Git Bash 여기에서 선택하여 git bash 생성을 연 다음 
> > > java -jar Buildtools.jar --rev 1.16.5를 실행하고 기다리면 빌드가 완료됩니다.
> > 
> > 
> > 저거 아무것도 몰라서 그런데 혹시 java -jar Buildtools.jar --rev 1.16.5가 뭔지 알수 있을까요
> 
> 문제 해결 사례면 이슈 닫아 주시고, 아닐 경우이를 따라주세요 :
> 
> ## BuildTools 실행
> **새 폴더를 만들고 그 안에서 BuildTools.jar를 실행하는 걸 권장합니다.**
> 
> BuildTools.jar가있는 디렉터리로 cmd를 이용해 이동 시키거나 그 디렉터리에서 Shift + 우클릭을 뒤 PowerShell을 켜서
> 
> `java -jar BuildTools.jar --rev 1.16.5` 명령을 입력합니다.
> 
> 대부분의 서버 관리자는 BuildTools를 사용하여 Spigot을 사용하는 작업을하지만, 개발자는 로컬 메이븐 저장소에 Spigot 관련 파일을 사용하는 경우가 있습니다.
> 
> BuildTools 작업이 마쳐지면를 재시도 `gradlew build`하세요.
> 
> #### 여담
> 이 댓글에 잘못된 정보가 달려 있거나 개선 할 점 등이 있다면 언제든 맨션하여 알려 주시면 감사하겠습니다.
> 
> 질문 작성자 분께 : 제가하기에는 좀 무례한 충고 일 수 있지만, 무조건 `작동 되지 않는다`라 이야기하지 마시고, 검색을 시도 시도합니다.

오홍 감사합니다
