### ISSUE TITLE
플러그인 적용

### ISSUE THREAD

**Issue by gilowdo** [noonmaru/inv-captive#5]
플러그인자체를 어떻게 플러그인파일에 적용하죠?

**Comment by thenist** [comment]
우선, 이슈는 질문하는곳이 아닌 문제점을 제보하는 곳 입니다 도배는 자제 해주세요,
그리고 기존 Issue는 닫아 주시기 바랍니다.
 플러그인 자체는 releases에 jar과 https://github.com/dmulloy2/ProtocolLib/releases 에서 ProtocolLib의 jar과 https://github.com/noonmaru/kotlin-plugin/releases 에서 Kotlin.jar를 서버의 plugins폴더에 넣으시기 바랍니다.

**Comment by thenist** [comment]
@gilowdo 이슈를 닫아주시기 바랍니다.
