### ISSUE TITLE
빌드 오류

### ISSUE THREAD

**Issue by yellow0519** [noonmaru/inv-captive#52]
빌드할떄 계속 e: E:\coding\inv-captive-master\build.gradle.kts:89:55: Unresolved reference: nullOutputStream 이오류가 떠요.

  Line 89:                         standardOutput = OutputStream.nullOutputStream()
                                                                 ^ Unresolved reference: nullOutputStream

  Line 90:                         errorOutput = OutputStream.nullOutputStream()
                                                              ^ Unresolved reference: nullOutputStream

**Comment by licker2689** [comment]
작업표시줄 검색에 환경변수 설정 들어가셔서 java_home 환경변수 설정을 11로 해주셔야 합니다, adopt jdk를 설치하시거나 jdk최신 버전을 설치해주세요!

**Comment by yellow0519** [comment]
오류설명 감사합니다!
