### ISSUE TITLE
핫바 강제해금버그

### ISSUE THREAD

**Issue by alsrjs0725** [noonmaru/inv-captive#8]
창고에 잡템을 넣은 후 마우스를 올려 배리어가 있는 핫바단축키(키보드 상단의 솟자) 또는 양손들기키를 누르면 창고에 있던 아이템이 핫바(또는 왼손)로 들어오며 핫바에 있는 배리어가 창고로 이동 이후 핫바가 사용 가능하게됩니다. 

환경 : 
paperbukkit 1.16.3 (paper-246)
플러그인:
Kotlin
ProtocolLib

**Comment by noonmaru** [comment]
수정되었습니다.
