### ISSUE TITLE
버전, 오류

### ISSUE THREAD

**Issue by eeddddyy** [noonmaru/inv-captive#9]
이거 inv-captive 서버 버전을 뭘로해야해요?
그리고 이거 아이템으로 해금하면 메세지가 안떠요.

**Comment by qogusdn1017** [comment]
버전은 1.16.3이며 Paper로 구동해야합니다.
블럭을 캐야 (BlockBreakEvent) 인벤토리가 해금됩니다.

**Comment by qogusdn1017** [comment]
이외의 문제 없을시 이슈 닫아주세요.

**Comment by devil0414** [comment]
지금은 버전이 1.16.4로 업데이트되었습니다~~

**Comment by thenist** [comment]
@devil0414 현재 1.16.4 빌드는 오류가 발생하여 아직 빌드 되지 않았습니다.
